name: Update Publications, then Build and Deploy to Github Pages

on:
  push:
    branches:
      - master  # Here source code branch is `master`, it could be other branch
  schedule:
    - cron: '30 23 1 * *' #Updates automatically on the 1st of every month
    
jobs:
  update_publications:
    name: Update the publication list
    runs-on: ubuntu-latest #Specifies the type of runner (might use windows-latest)
    steps:
      - name: Checkout Repo Contents
        uses: actions/checkout@v2.4.2
        
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.0'
        
      - name: Install python packages
        run: |
              python -m pip install --upgrade pip
              pip install -r pub_update_requirements.txt
              
      - name: Run SerpApi script
        run: python populate_publications.py
        
      - name: Run Scholar scraper for additional info
        run: python format_publications.py
    
      - name: Commit files for saving
        run:  |
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
              git add -A
              git commit -m "Publication update from action ${{ github.sha }}" -a
              
      - name: Push to master
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master #Designate branch to push to
          
  build_and_deploy:
    needs: update_publications
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Use GitHub Actions' cache to cache dependencies on servers
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Use GitHub Deploy Action to build and deploy to Github
      - uses: jeffreytse/jekyll-deploy-action@v0.3.1
        with:
          provider: 'github'
          token: ${{ secrets.GITHUB_TOKEN }} # It's your Personal Access Token(PAT)
          repository: ''             # Default is current repository
          branch: 'gh-pages'         # Default is gh-pages for github provider
          jekyll_src: './'           # Default is root directory
          jekyll_cfg: '_config.yml'  # Default is _config.yml
          jekyll_baseurl: ''         # Default is according to _config.yml
          bundler_ver: '>=0'         # Default is latest bundler version
          cname: ''                  # Default is to not use a cname
          actor: ''                  # Default is the GITHUB_ACTOR
          pre_build_commands: ''     # Installing additional dependencies (Arch Linux)
